name: farmacia_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  provider: ^6.1.5+1
  http: ^1.2.2
  file_picker: ^10.3.2
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  supabase_flutter: ^2.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 

flutter_native_splash:
  color: "FFFFFF"
  image: assets/images/logo_pequena.png
  android_12:
    color: "FFFFFF"
    image: assets/images/logo_pequena.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
